### PR TITLE
Special case ClusterLogging so it properly generates the types

### PR DESCRIPTION
**Pull request by aschleck**
Fixes https://github.com/pulumi/pulumi-aws-native/issues/644, this special case lines up with the suggested solution here https://github.com/pulumi/pulumi-aws-native/issues/644#issuecomment-1300987893

I don't see a good way to automatically check for collisions unfortunately, but someone who understands this code better than me may see a good way.

### CODE REVIEW

**Comment by aschleck** [comment]
@danielrbradley would you be a good reviewer for this? I don't seem to have permissions to assign the review to you but I'm hoping someone can look at this.

**Comment by danielrbradley** [comment]
@aschleck just going to wait on the acceptance tests, then should be good to merge this. Thank you for your help tackling this very tricky bug! 🙇

**Review by danielrbradley — APPROVED** [review]

**Comment by aschleck** [comment]
Thank you so much Daniel for your help with this and fixing up the PR!

**Pull request merged**
