### PR TITLE
Fix generation of type definitions using OneOf

### PR DESCRIPTION
**Pull request by mjeffryes**
The logic for detecting object types when traversing a ref in the schema was too aggressive; it was eating types using OneOf/AllOf and turning them into empty objects. With this change, it only traps objects that are explicitly typed as "object" or that have properties

Fixes: #881 

## Testing
Added some new examples cases to the unittests, scanned the schema changes

### CODE REVIEW

**Comment by mjeffryes** [comment]
The schema-tools report isn't really doing a good job with this diff. The types that are "missing" are where we were mistakenly creating objects. The inputs/outputs that changed to "" actually changed to `OneOf`s

There are a couple cases where types changed to "pulumi.json#/Any". I checked each of these and they all use "propertyPatterns"; it looks like jsschema is not able to parse the Regex on a handful of these.

**Review by iwahbe — COMMENTED** [review]
Are we assuming that `typeSchema.Type[0]` is representative of all type schemas?

**Comment by mjeffryes** [comment]
> Are we assuming that `typeSchema.Type[0]` is representative of all type schemas?

It's not (That's why we had this issue to begin with: OneOf types often don't have a `type` field at the top level), but we don't need to unambiguously identify all the different types here; we just need to identify things that are "object" shaped  (mostly so we can avoid tacking "Properties" onto the name, which is what happens when we recurse). Objects are identified by schemas that have `type == "object"` or have non-empty `properties` or non-empty `propertiesPattern`.

To be fair, I don't love the way this code is structured; it's trying to do everything in one pass: convert JSSchema types into pulumi types, rename everything and introduce references for intermediate objects. I think we could make the whole thing easier to reason about and test if we split it into at least two passes, but I didn't feel like I had the time to do that right now.

**Review by iwahbe — APPROVED** [review]

**Review by mikhailshilkov — APPROVED** [review]
LGTM, that was surprisingly straightforward.

**Pull request merged**
